### ISSUE TITLE
Org Admin of Pending Org Should get redirected to org admin dashboard when they submit their request to register their org

### ISSUE THREAD

**Issue by allindow** [allindow/the_pivot#119]
I'm thinking it's fine if they can add/edit recipients, add to their team, and edit their org, if that functionality already exists.

Just confirm that pending organization and pending recipients do not show up anywhere else, such as All Recipients or the organizations index

**Comment by chompasina** [comment]
We changed this story so that users who submit new organizations aren't org admins, just registered users and they are redirected to their user show page. I'm moving this to develop since we've written this code.
