### ISSUE TITLE
Registered User Submits Request for New Cause

### ISSUE THREAD

**Issue by allindow** [allindow/the_pivot#26]
As a guest user,
when I visit the homepage
and I click on "Register Organization" 
I should be taken to the organization registration page
and I should see a description of the approval process,
and  when I fill in my organization name,
and I fill in my organization description,
and I click on Register Organization,
I should be taken to my organization dashboard,
and I should see my status as Pending,
and I should not see Manage Team

**Comment by lcmccartney** [comment]
As a registered user,
when I log in,
and I click on "Register Organization" 
I should be taken to the organization registration page
and I should see a description of the approval process,
and when I fill in my organization name,
and I fill in my organization description,
and I click on Submit,
I should be taken to my organization dashboard,
and I should see my status as Pending,
and I should not see Manage Team
